### ISSUE TITLE
When inserting a Genealogy Link using Editor - TinyMCE the link is placed twice

### ISSUE THREAD

**Issue by felixkat** [joaktree/J5#1]
When inserting a Genealogy Link using Editor - TinyMCE the link is placed twice.  This **doesn't** happen using Editor - JCE.

Example

`
{joaktree person|2|I191|content}{joaktree person|2|I191|content}`

Glad to see this project alive.  😃

**Comment by conseilgouz** [comment]
Hi,
Thank you for reporting this.
I'll check this as soon as possible.
Kind regards,
Pascal

**Comment by felixkat** [comment]
Hi,  

I've updated the issue as it seems this is only happening on TinyMCE

**Comment by felixkat** [comment]
Perfect, tested and working.  👍
