### ISSUE TITLE
Folder isn't being created when creating a new theme

### ISSUE THREAD

**Issue by felixkat** [joaktree/J5#2]
### Folder isn't being created when creating a new theme

No error messages appear when creating a theme but are shown when trying to edit or delete the theme.

Tested on standard linux hosting.

**Comment by conseilgouz** [comment]
Hi,
Version 2.0.3-rc fixes this issue and corrects some other ones.
https://github.com/joaktree/J5/releases/download/2.0.3-rc/J5-2.0.3-rc.zip
Pascal

**Comment by felixkat** [comment]
Perfect, all working.  👍
