### ISSUE TITLE
Geocode button results in a bad URL

### ISSUE THREAD

**Issue by felixkat** [joaktree/J5#3]
![image](https://github.com/user-attachments/assets/f7159904-cbab-463b-b86d-6a009c6ee77b)

Geocode button results in a bad URL.

![image](https://github.com/user-attachments/assets/e3412921-892b-4ea5-9b63-2138591867cd)

It does this with either map service.

**Comment by conseilgouz** [comment]
Hi,

Please give a copy of Joaktree configuration, Maps Services tab.

Is "geocode by subdivision" parameter set to yes or no ?  try to set it to no.

![geocode](https://github.com/user-attachments/assets/0420b6e8-ebca-468a-b80f-0829c91b4333)

Pascal

**Comment by felixkat** [comment]
Hi,

After some testing, it appears the main issue occurs if you set interactive map to 'no'. 

The error message will vary depending if you have details in the country and language code.  The original screenshot I sent you didn't have country or language code entered.

The following settings:-

![image](https://github.com/user-attachments/assets/b6c60d5b-bb99-4a04-b248-3b00573d7f19)


Produce the following error.

![image](https://github.com/user-attachments/assets/694ce0c8-b35d-43bb-a91f-b48f71551cfe)

**Comment by fontanil** [comment]
Sorry! 
With rc3, subdivision activated or not, I can't geocode with Google nor OpenStreetMap.
If I disable geocoding, I get errors on sources that I didn't have at the time.

Robert

**Comment by fontanil** [comment]
No error with RC2 version (Google no subdivision).

**Comment by felixkat** [comment]
This was tested with RC3 as pictured with geocode set to no.

The error only appears if items haven't been processed, so I performed `UPDATE #___joaktree_locations SET `indServerProcessed`='0' `for testing. 

I will test again later.

**Comment by conseilgouz** [comment]
Hi, 

I disabled indServerProcessed variable in https://github.com/joaktree/J5/releases/download/2.0.3-rc4/J5-2.0.3-rc4.zip

@fontanil : It seems that it does not work anymore and I still do not understand what it's usefull anyway.

Geocoding with OpenStreetMap is now correct and GoogleMap should be OK too.

Pascal

**Comment by felixkat** [comment]
I thought it was there so only locations that haven't been geocoded were processed. so gecoding can be done in smaller batches without starting from the beginning. 

So if all records are set to indServerProcessed"="1" then geocding isn't performed.

I could be wrong though, I'm still learning Joaktree  😄

**Comment by conseilgouz** [comment]
Hi,
I'm not a joaktree expert, I just did Joomla 5 migration.
There are a bunch of functions I did not test and some I don't see their purposes.
Thank you for yor help in testing.
Pascal

**Comment by felixkat** [comment]
I'm happy to help with the testing as I have a family members website that I'm using it to test on.
